//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToursApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyReception
    {
        public int Id { get; set; }
        public string CouponNum { get; set; }
        public string Data { get; set; }
        public string Cost { get; set; }
        public int Diagnos { get; set; }
        public int Doctor { get; set; }
        public int Patient { get; set; }
    
        public virtual Diagno Diagno { get; set; }
        public virtual Doctor Doctor1 { get; set; }
        public virtual Patient Patient1 { get; set; }
    }
}
